version: "3.8"

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID:-$(stat -c '%g' /var/run/docker.sock)}
    image: github-runner
    container_name: github-runner
    environment:
      RUNNER_URL: ${RUNNER_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      LABELS: ${LABELS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
